name: ab-data-validator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - biopython=1.87
  - bioconda::anarci==2021.02.04
  - bioconda::muscle=5.*
  - openpyxl=3.1.*
  - pytest
  - pip
